FROM node:23.11.1-alpine
WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install && npm install -g serve
RUN npm install --save-dev @types/react @types/react-dom react-hook-form


COPY . .

RUN npm run build

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]
