# Generate ssl certificate (kept from main)
FROM nginx:1.28.0

RUN apt-get update && apt-get install -y \
    openssl && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/selfsigned.key \
    -out /etc/nginx/ssl/selfsigned.crt \
    -subj "/C=US/ST=State/L=City/O-Organization/CN=matcha.42"

COPY nginx.conf /etc/nginx/nginx.conf
COPY matcha.conf /etc/nginx/conf.d/matcha.conf
COPY proxy-headers.conf /etc/nginx/proxy-headers.conf

EXPOSE 80 443