//Contains the logic to register a user, login a user, and get user data

//Importing necessary modules
const bcrypt = require('bcrypt'); //Cryptographic library for hashing passwords
const jwt = require('jsonwebtoken'); //JWT
const db = require('../models');

//Importing the User model from the database
const User = db.users;

const signup = async(req, res) => {
    console.log("Request body:", req.body);
    try {
        const { username, email, password } = req.body;
        const data = {
            id: null, //ID will be auto-generated by the database
            username,
            email,
            password: await bcrypt.hash(password, 10) //Hashing the password using bcrypt
        };
        console.log("Data to be saved:", data);
        const user = await User.create(data); //Creating a new user in the database
        console.log("User created:", user);

        //If the user is created successfully, we generate a JWT token and set it as a cookie
        if (user) {
            if (!process.env.JWT_SECRET) {
                console.log('JWT_SECRET is not defined in environment variables.');
                return res.status(500).json({ message: 'Internal server error: JWT secret not set.' });
            }
            const token = jwt.sign({ id: user.id }, process.env.JWT_SECRET, { expiresIn: 5 * 60 }); //Creating a JWT token for 5 minutes
            res.cookie('token', token, { httpOnly: true, maxAge: 1 * 24 * 60 * 60});
            console.log("user", JSON.stringify(user, null, 2)); //Logging the user data to the console
            console.log("token", token);
        return res.status(201).send(user); //Sending the user data as a response
        }
        else {
            return res.status(400).json({ message: 'User creation failed' }); //If user creation fails, we return a 400 status code
        }
    }
    catch (error) {
        return res.status(500).json({ message: 'Internal server error' });
    }
};

const login = async (req, res) => {
 try {
const { username, password } = req.body;

   const user = await User.findOne({
     where: {
     username: username
   } 
     
   });
   console.log("User found:", user);

   //if user email is found, compare password with bcrypt
   if (user) {
     const isSame = await bcrypt.compare(password, user.password);
    console.log("Password match:", isSame);

     //if password is the same
      //generate token with the user's id and the secretKey in the env file

     // If the password matches, we generate a JWT token and set it as a cookie

     if (isSame) {
       let token = jwt.sign({ id: user.id }, process.env.JWT_SECRET, {
         expiresIn: 5 * 60,
       });

       console.log("Token generated:", token);

       res.cookie("jwt", token, { maxAge: 1 * 24 * 60 * 60, httpOnly: true });
       console.log("user", JSON.stringify(user, null, 2));
       console.log("token", token);
       //send user data
       console.log("User logged in successfully");
       return res.status(201).send(user);
     } else {
       console.log("Authentication failed ; password does not match");
       return res.status(401).send("Authentication failed");
     }
   } else {
     console.log("Authentication failed ; user not found");
     return res.status(401).send("Authentication failed");
   }
 } catch (error) {
   console.log(error);
 }
};


module.exports = {
    signup,
    login,
};

